const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const PRESETS={'2.3':{speed:2.3,gainDb:-4},'2.5':{speed:2.5,gainDb:-6},'2.7':{speed:2.7,gainDb:-8}};
const state={preset:'2.5',files:[],history:[],ffmpeg:null,processed:Number(localStorage.getItem('cbProcessed')||0)};
$('#processedCount').textContent=state.processed;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
$$('.preset').forEach(b=>b.onclick=()=>{state.preset=b.dataset.preset;$$('.preset').forEach(x=>x.classList.toggle('active',x===b));const p=PRESETS[state.preset];$('#activePresetLabel').textContent=`SPEED ${p.speed}X · AMPLIFY ${p.gainDb} DB`;});
const input=$('#fileInput'),drop=$('#dropzone'),convertBtn=$('#convertBtn');
drop.onclick=()=>input.click();drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();addFiles([...e.dataTransfer.files])};input.onchange=()=>addFiles([...input.files]);
function validAudio(f){return /\.(mp3|wav|m4a|ogg|flac|aac)$/i.test(f.name)||f.type.startsWith('audio/')}
function addFiles(files){const valid=files.filter(validAudio);state.files.push(...valid);renderQueue();if(valid.length!==files.length)toast('Sebagian file bukan format audio yang didukung.');}
function renderQueue(){const q=$('#queue'),list=$('#queueList');q.hidden=!state.files.length;convertBtn.disabled=!state.files.length;list.innerHTML='';state.files.forEach((f,i)=>{const d=document.createElement('div');d.className='queue-item';d.innerHTML=`<span>${f.name} <small>(${(f.size/1024/1024).toFixed(2)} MB)</small></span><button aria-label="remove">×</button>`;d.querySelector('button').onclick=()=>{state.files.splice(i,1);renderQueue()};list.appendChild(d)});}
$('#clearQueue').onclick=()=>{state.files=[];renderQueue()};
async function getEngine(){if(state.ffmpeg)return state.ffmpeg;const {FFmpeg}=window.FFmpegWASM||{};const util=window.FFmpegUtil||{};if(!FFmpeg||!util.toBlobURL)throw new Error('Audio engine gagal dimuat. Coba refresh halaman.');const ffmpeg=new FFmpeg();ffmpeg.on('progress',({progress})=>{$('#progressFill').style.width=`${Math.max(0,Math.min(100,progress*100))}%`});$('#engineStatus').textContent='Memuat audio engine...';const base='https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.6/dist/umd';await ffmpeg.load({coreURL:await util.toBlobURL(`${base}/ffmpeg-core.js`,'text/javascript'),wasmURL:await util.toBlobURL(`${base}/ffmpeg-core.wasm`,'application/wasm')});$('#engineStatus').textContent='Audio engine ready · local browser processing.';state.ffmpeg=ffmpeg;return ffmpeg;}
async function convertOne(file,p,index){const ffmpeg=await getEngine();const {fetchFile}=window.FFmpegUtil;const ext=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'');const id=`${Date.now()}-${index}`;const inputName=`input-${id}.${ext}`;const outputName=`output-${id}.ogg`;await ffmpeg.writeFile(inputName,await fetchFile(file));const rate=Math.round(48000*p.speed);await ffmpeg.exec(['-y','-i',inputName,'-vn','-af',`aresample=48000,asetrate=${rate},aresample=48000,volume=${p.gainDb}dB`,'-ar','48000','-ac','2','-c:a','libvorbis','-q:a','5',outputName]);const data=await ffmpeg.readFile(outputName);await ffmpeg.deleteFile(inputName).catch(()=>{});await ffmpeg.deleteFile(outputName).catch(()=>{});const blob=new Blob([data.buffer],{type:'audio/ogg'});return{title:`${p.speed}x-${file.name.replace(/\.[^.]+$/,'')}.ogg`,speed:p.speed,gainDb:p.gainDb,size:blob.size,createdAt:Date.now(),url:URL.createObjectURL(blob)}}
convertBtn.onclick=async()=>{if(!state.files.length)return;const batch=[...state.files],p=PRESETS[state.preset];convertBtn.disabled=true;$('#progressBar').hidden=false;try{await getEngine();for(let i=0;i<batch.length;i++){$('#convertBtnText').textContent=`Processing ${i+1}/${batch.length}`;$('#progressFill').style.width='0%';const result=await convertOne(batch[i],p,i);state.history.unshift(result);state.processed++;localStorage.setItem('cbProcessed',String(state.processed));$('#processedCount').textContent=state.processed;showResult(result);renderHistory();}state.files=[];renderQueue();toast('Semua audio selesai dikonversi.')}catch(err){console.error(err);toast(err.message||'Conversion gagal.')}finally{$('#convertBtnText').textContent='Convert to Chipmunk OGG';convertBtn.disabled=!state.files.length;}};
function showResult(x){$('#resultPanel').hidden=false;$('#editedChip').textContent=`Audio edited (${x.speed}x · ${x.gainDb} dB)`;$('#resultSpeed').textContent=`${x.speed}x`;$('#currentResult').innerHTML=`<div class="result-card"><div class="track-row"><div class="track-icon">♫</div><div><strong>${x.title}</strong><div>OGG · ${x.speed}x · ${x.gainDb} dB · ${(x.size/1024/1024).toFixed(2)} MB</div></div></div><audio controls src="${x.url}"></audio><a class="download-btn" href="${x.url}" download="${x.title}">⇩ Download Audio (.ogg)</a></div>`;}
function renderHistory(){const body=$('#historyBody');body.innerHTML='';$('#historyCount').textContent=`${state.history.length} entries`;$('#emptyHistory').hidden=!!state.history.length;state.history.forEach((x,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${x.title}</td><td>${x.speed}x · ${x.gainDb} dB</td><td>${(x.size/1024/1024).toFixed(2)} MB</td><td>${new Date(x.createdAt).toLocaleString('id-ID')}</td><td><a class="table-action" href="${x.url}" download="${x.title}">⇩</a></td>`;body.appendChild(tr)});}
$('#clearHistory').onclick=()=>{state.history.forEach(x=>URL.revokeObjectURL(x.url));state.history=[];renderHistory();toast('History dibersihkan.');};
renderQueue();renderHistory();
